spring.application.name=discord-bot

#Database config
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mariadb://${db:localhost}:3306/discordbot
spring.datasource.username=root
spring.datasource.password=
SPRING.DATASOURCE.DRIVER-CLASS-NAME=org.mariadb.jdbc.Driver
spring.jpa.open-in-view=false
